// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcp/v1/annotations.proto

package mcpv1

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_mcp_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         58800,
		Name:          "mcp.v1.tool_name",
		Tag:           "bytes,58800,opt,name=tool_name",
		Filename:      "mcp/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// tool_name overrides the derived MCP tool name for this method.
	//
	// By default the tool name is the method's full proto name with dots
	// replaced by underscores, hash-truncated to 64 characters when too
	// long. Set this option to publish the method under a stable,
	// human-chosen name instead, e.g.:
	//
	//	rpc GetEquityResearchReport(...) returns (...) {
	//	  option (mcp.v1.tool_name) = "get_equity_research_report";
	//	}
	//
	// The value must match ^[a-z_][a-z0-9_-]{0,63}$ — lowercase
	// snake/kebab case within every LLM provider's function-name rules
	// (Gemini requires a leading letter or underscore; OpenAI restricts
	// the charset; 64 is the strictest length limit). Lowercase is
	// enforced so a configured name can never resemble a derived
	// "<Service>Service_<Method>" name and is therefore passed through
	// untouched by downstream de-mangling heuristics. protoc-gen-go-mcp
	// fails code generation on an invalid value, or on a duplicate name
	// within the same service (one service is one MCP server
	// registration; different services may reuse a name).
	//
	// optional string tool_name = 58800;
	E_ToolName = &file_mcp_v1_annotations_proto_extTypes[0]
)

var File_mcp_v1_annotations_proto protoreflect.FileDescriptor

const file_mcp_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x18mcp/v1/annotations.proto\x12\x06mcp.v1\x1a google/protobuf/descriptor.proto:=\n" +
	"\ttool_name\x12\x1e.google.protobuf.MethodOptions\x18\xb0\xcb\x03 \x01(\tR\btoolNameB<Z:github.com/redpanda-data/protoc-gen-go-mcp/pkg/mcpv1;mcpv1b\x06proto3"

var file_mcp_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}

var file_mcp_v1_annotations_proto_depIdxs = []int32{
	0, // 0: mcp.v1.tool_name:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_v1_annotations_proto_init() }
func file_mcp_v1_annotations_proto_init() {
	if File_mcp_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_annotations_proto_rawDesc), len(file_mcp_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_annotations_proto_goTypes,
		DependencyIndexes: file_mcp_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_mcp_v1_annotations_proto_extTypes,
	}.Build()
	File_mcp_v1_annotations_proto = out.File
	file_mcp_v1_annotations_proto_goTypes = nil
	file_mcp_v1_annotations_proto_depIdxs = nil
}
