// Copyright 2025 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"fmt"
	"go/token"
	"path"
	"path/filepath"
	"text/template"

	"github.com/redpanda-data/protoc-gen-go-mcp/pkg/gen"
	"github.com/redpanda-data/protoc-gen-go-mcp/pkg/runtime"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	GeneratedFilenameExtension = ".pb.mcp.go"
)

type FileGenerator struct {
	f   *protogen.File
	gen *protogen.Plugin

	gf *protogen.GeneratedFile
}

func NewFileGenerator(f *protogen.File, gen *protogen.Plugin) *FileGenerator {
	gen.SupportedFeatures |= uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	return &FileGenerator{f: f, gen: gen}
}

const fileTemplate = `// Code generated by protoc-gen-mcp-go. DO NOT EDIT.
// source: {{ .SourcePath }}

package {{ .GoPackage }}

import (
  "context"
  "encoding/json"
  "google.golang.org/protobuf/encoding/protojson"
  "connectrpc.com/connect"
  grpc "google.golang.org/grpc"
  "github.com/redpanda-data/protoc-gen-go-mcp/pkg/runtime"
)


var (
{{- range $key, $val := .Tools }}
  {{$key}}Tool = {{ printf "%#v" $val }}
{{- end }}
)

{{- range $serviceName, $methods := .Services }}
// {{$serviceName}}Server is compatible with the grpc-go server interface.
type {{$serviceName}}Server interface {
  {{- range $methodName, $tool := $methods }}
  {{$methodName}}(ctx context.Context, req *{{$tool.RequestType}}) (*{{$tool.ResponseType}}, error)
  {{- end }}
}
{{ end }}

{{- range $key, $val := .Services }}
// Register{{$key}}Handler registers standard MCP handlers for {{$key}}
func Register{{$key}}Handler(s runtime.MCPServer, srv {{$key}}Server, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}Tool := {{$key}}_{{$tool_name}}Tool
  {{$tool_name}}Tool = runtime.ApplyConfig({{$tool_name}}Tool, config)

  s.AddTool({{$tool_name}}Tool, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    // Rewrite oneof discriminated wrappers and recursion placeholders into the
    // protojson-native shape. Errors are model-readable for self-correction.
    if err := runtime.DecodeArguments(req.ProtoReflect().Descriptor(), message); err != nil {
      return runtime.NewToolResultError(err.Error()), nil
    }

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := srv.{{$tool_name}}(ctx, &req)
    if err != nil {
      return runtime.HandleError(err)
    }

    structured, err := runtime.EncodeMessage(resp)
    if err != nil {
      return nil, err
    }

    return runtime.NewToolResultJSON(structured), nil
  })
  {{- end }}
}
{{- end }}

{{- range $serviceName, $methods := .Services }}
// {{$serviceName}}Client is compatible with the grpc-go client interface.
type {{$serviceName}}Client interface {
  {{- range $methodName, $tool := $methods }}
  {{$methodName}}(ctx context.Context, req *{{$tool.RequestType}}, opts ...grpc.CallOption) (*{{$tool.ResponseType}}, error)
  {{- end }}
}
{{ end }}


{{- range $serviceName, $methods := .Services }}
// Connect{{$serviceName}}Client is compatible with the connectrpc-go client interface.
type Connect{{$serviceName}}Client interface {
  {{- range $methodName, $tool := $methods }}
  {{$methodName}}(ctx context.Context, req *connect.Request[{{$tool.RequestType}}]) (*connect.Response[{{$tool.ResponseType}}], error)
  {{- end }}
}
{{ end }}

{{- range $key, $val := .Services }}
// ForwardToConnect{{$key}}Client registers a connectrpc client, to forward MCP calls to it.
func ForwardToConnect{{$key}}Client(s runtime.MCPServer, client Connect{{$key}}Client, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}Tool := {{$key}}_{{$tool_name}}Tool
  {{$tool_name}}Tool = runtime.ApplyConfig({{$tool_name}}Tool, config)

  s.AddTool({{$tool_name}}Tool, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    if err := runtime.DecodeArguments(req.ProtoReflect().Descriptor(), message); err != nil {
      return runtime.NewToolResultError(err.Error()), nil
    }

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := client.{{$tool_name}}(ctx, connect.NewRequest(&req))
    if err != nil {
      return runtime.HandleError(err)
    }

    structured, err := runtime.EncodeMessage(resp.Msg)
    if err != nil {
      return nil, err
    }
    return runtime.NewToolResultJSON(structured), nil
  })
  {{- end }}
}
{{- end }}

{{- range $key, $val := .Services }}
// ForwardTo{{$key}}Client registers a gRPC client, to forward MCP calls to it.
func ForwardTo{{$key}}Client(s runtime.MCPServer, client {{$key}}Client, opts ...runtime.Option) {
  config := runtime.NewConfig()
  for _, opt := range opts {
    opt(config)
  }

  {{- range $tool_name, $tool_val := $val }}
  {{$tool_name}}Tool := {{$key}}_{{$tool_name}}Tool
  {{$tool_name}}Tool = runtime.ApplyConfig({{$tool_name}}Tool, config)

  s.AddTool({{$tool_name}}Tool, func(ctx context.Context, request *runtime.CallToolRequest) (*runtime.CallToolResult, error) {
    var req {{$tool_val.RequestType}}

    message := request.Arguments

    // Extract extra properties if configured
    for _, prop := range config.ExtraProperties {
      if propVal, ok := message[prop.Name]; ok {
        ctx = context.WithValue(ctx, prop.ContextKey, propVal)
      }
    }

    if err := runtime.DecodeArguments(req.ProtoReflect().Descriptor(), message); err != nil {
      return runtime.NewToolResultError(err.Error()), nil
    }

    marshaled, err := json.Marshal(message)
    if err != nil {
      return nil, err
    }

    if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(marshaled, &req); err != nil {
      return nil, err
    }

    resp, err := client.{{$tool_name}}(ctx, &req)
    if err != nil {
      return runtime.HandleError(err)
    }

    structured, err := runtime.EncodeMessage(resp)
    if err != nil {
      return nil, err
    }
    return runtime.NewToolResultJSON(structured), nil
  })
  {{- end }}
}
{{- end }}


`

type TplParams struct {
	PackageName string
	SourcePath  string
	GoPackage   string
	Tools       map[string]runtime.Tool
	Services    map[string]map[string]Tool
}

type Tool struct {
	RequestType  string
	ResponseType string
	MCPTool      runtime.Tool
}

// Delegate to gen package - kept for backward compatibility with tests in this package.
var (
	kindToType          = gen.KindToType
	cleanComment        = gen.CleanComment
	MangleHeadIfTooLong = gen.MangleHeadIfTooLong
	Base36String        = gen.Base36String
)

// messageSchema delegates to the gen package.
func (g *FileGenerator) messageSchema(md protoreflect.MessageDescriptor) map[string]any {
	return gen.MessageSchema(md, gen.SchemaOptions{})
}

// getType delegates to the gen package.
func (g *FileGenerator) getType(fd protoreflect.FieldDescriptor) map[string]any {
	return gen.FieldSchema(fd, gen.SchemaOptions{})
}

func (g *FileGenerator) Generate(packageSuffix string) {
	file := g.f
	if len(g.f.Services) == 0 {
		return
	}
	goImportPath := file.GoImportPath
	if packageSuffix != "" {
		if !token.IsIdentifier(packageSuffix) {
			g.gen.Error(fmt.Errorf("package_suffix %q is not a valid Go identifier", packageSuffix))
			return
		}
		file.GoPackageName += protogen.GoPackageName(packageSuffix)
		generatedFilenamePrefixToSlash := filepath.ToSlash(file.GeneratedFilenamePrefix)
		file.GeneratedFilenamePrefix = path.Join(
			path.Dir(generatedFilenamePrefixToSlash),
			string(file.GoPackageName),
			path.Base(generatedFilenamePrefixToSlash),
		)
		goImportPath = protogen.GoImportPath(path.Join(
			string(file.GoImportPath),
			string(file.GoPackageName),
		))
	}

	g.gf = g.gen.NewGeneratedFile(
		file.GeneratedFilenamePrefix+GeneratedFilenameExtension,
		goImportPath,
	)
	if packageSuffix != "" {
		g.gf.Import(file.GoImportPath)
	}

	fileTpl := fileTemplate
	tpl, err := template.New("gen").Parse(fileTpl)
	if err != nil {
		g.gen.Error(err)
		return
	}

	services := map[string]map[string]Tool{}
	tools := map[string]runtime.Tool{}

	for _, svc := range g.f.Services {
		s := map[string]Tool{}
		// Duplicate tool names are checked per service: one service is
		// one Register<Service>Handler call, i.e. one MCP server's tool
		// set. Wider scopes are not statically decidable — two different
		// services may legitimately both name a tool "get_dashboard",
		// they just can't be registered on the same server. Derived
		// names are unique by construction (proto full names are), so a
		// duplicate can only come from the (mcp.v1.tool_name) option.
		seenToolNames := map[string]string{}
		for _, meth := range svc.Methods {
			if meth.Desc.IsStreamingClient() || meth.Desc.IsStreamingServer() {
				continue
			}

			comment := string(meth.Comments.Leading)

			// A configured (mcp.v1.tool_name) must be valid on every
			// LLM provider; fail generation instead of emitting a name
			// a provider will reject at request time.
			if cfg, ok := gen.ConfiguredToolName(meth.Desc); ok {
				if err := gen.ValidateToolName(cfg); err != nil {
					g.gen.Error(fmt.Errorf("%s: (mcp.v1.tool_name): %w", meth.Desc.FullName(), err))
					return
				}
			}

			tool := gen.ToolForMethod(meth.Desc, comment)

			if prev, dup := seenToolNames[tool.Name]; dup {
				g.gen.Error(fmt.Errorf("duplicate tool name %q in service %s: claimed by both %s and %s", tool.Name, svc.Desc.FullName(), prev, meth.Desc.FullName()))
				return
			}
			seenToolNames[tool.Name] = string(meth.Desc.FullName())

			s[meth.GoName] = Tool{
				RequestType:  g.gf.QualifiedGoIdent(meth.Input.GoIdent),
				ResponseType: g.gf.QualifiedGoIdent(meth.Output.GoIdent),
				MCPTool:      tool,
			}
			tools[svc.GoName+"_"+meth.GoName] = tool
		}
		services[string(svc.Desc.Name())] = s
	}

	params := TplParams{
		PackageName: string(g.f.Desc.Package()),
		SourcePath:  g.f.Desc.Path(),
		GoPackage:   string(g.f.GoPackageName),
		Services:    services,
		Tools:       tools,
	}
	err = tpl.Execute(g.gf, params)
	if err != nil {
		g.gen.Error(err)
	}
}
